### ISSUE TITLE
Use Node 20

### ISSUE THREAD

**Issue by humbertowoody** [Saionaro/extract-package-version#21]
Hello! First things first, thank you for this project! 

Recently I noticed that my workflows are showing the following warning: 

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: Saionaro/extract-package-version@v1.2.1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

I see this action is using Node 18, so maybe the update to Node 20 is straightforward.

Anyways, thanks in advance!

**Comment by saionaro** [comment]
@humbertowoody hey! Thanks for bumping me!
node20 update is included in v1.3.0
